export let emojis = [
    { id: 1, name: 'Grinning Face', code: '1F600' },
    { id: 2, name: 'Grinning Face With Big Eyes', code: '1F601' },
    { id: 3, name: 'Face With Tears of Joy', code: '1F602' },
    { id: 4, name: 'Smiling Face With Open Mouth', code: '1F603' },
    { id: 5, name: 'Smiling Face With Open Mouth and Smiling Eyes', code: '1F604' },
    { id: 6, name: 'Smiling Face With Open Mouth and Cold Sweat', code: '1F605' },
    { id: 7, name: 'Smiling Face With Open Mouth and Tightly Closed Eyes', code: '1F606' },
    { id: 8, name: 'Smiling Face With Halo', code: '1F607' },
    { id: 9, name: 'Smiling Face With Horns', code: '1F608' },
    { id: 10, name: 'Winking Face', code: '1F609' },
    { id: 11, name: 'Smiling Face With Smiling Eyes', code: '1F60A' },
    { id: 12, name: 'Face Savoring Delicious Food', code: '1F60B' },
    { id: 13, name: 'Relieved Face', code: '1F60C' },
    { id: 14, name: 'Smiling Face With Heart-Shaped Eyes', code: '1F60D' },
    { id: 15, name: 'Smiling Face With Sunglasses', code: '1F60E' },
    { id: 16, name: 'Smirking Face', code: '1F60F' },
    { id: 17, name: 'Neutral Face', code: '1F610' },
    { id: 18, name: 'Expressionless Face', code: '1F611' },
    { id: 19, name: 'Unamused Face', code: '1F612' },
    { id: 20, name: 'Face With Cold Sweat', code: '1F613' },
    { id: 21, name: 'Pensive Face', code: '1F614' },
    { id: 22, name: 'Confused Face', code: '1F615' },
    { id: 23, name: 'Confounded Face', code: '1F616' },
    { id: 24, name: 'Kissing Face', code: '1F617' },
    { id: 25, name: 'Face With Stuck-out Tongue', code: '1F618' },
    { id: 26, name: 'Face With Stuck-out Tongue and Winking Eye', code: '1F619' },
    { id: 27, name: 'Face With Stuck-out Tongue and Tightly Closed Eyes', code: '1F61A' },
    { id: 28, name: 'Disappointed Face', code: '1F61E' },
    { id: 29, name: 'Worried Face', code: '1F61F' },
    { id: 30, name: 'Angry Face', code: '1F620' },
    { id: 31, name: 'Pouting Face', code: '1F621' },
    { id: 32, name: 'Crying Face', code: '1F622' },
    { id: 33, name: 'Persevering Face', code: '1F623' },
    { id: 34, name: 'Face With Steam From Nose', code: '1F624' },
    { id: 35, name: 'Face With Steam From Nose', code: '1F624'},
    { id: 36, name: 'Sad but Relieved Face', code: '1F625'},
    { id: 37, name: 'Face With Open Mouth', code: '1F626'},
    { id: 38, name: 'Hushed Face', code: '1F627'},
    { id: 39, name: 'Sleepy Face', code: '1F628'},
    { id: 40, name: 'Tired Face', code: '1F629'},
    { id: 41, name: 'Grimacing Face', code: '1F62A'},
    { id: 42, name: 'Loudly Crying Face', code: '1F62D'},
    { id: 43, name: 'Face With Open Mouth and Cold Sweat', code: '1F630'},
    { id: 44, name: 'Face Screaming in Fear', code: '1F631'},
    { id: 45, name: 'Astonished Face', code: '1F632'},
    { id: 46, name: 'Flushed Face', code: '1F633'},
    { id: 47, name: 'Sleeping Face', code: '1F634'},
    { id: 48, name: 'Dizzy Face', code: '1F635'},
    { id: 49, name: 'Face Without Mouth', code: '1F636'},
    { id: 50, name: 'Face With Medical Mask', code: '1F637'},
]